version: "3"

services:

  runtime-setup:
    image: swift-crypto:18.04-5.4
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.4"

  test:
    image: swift-crypto:18.04-5.4
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  cmake:
    image: swift-crypto:18.04-5.4

  shell:
    image: swift-crypto:18.04-5.4
