version: "3"

services:

  runtime-setup:
    image: swift-crypto:20.04-5.3
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.3"

  test:
    image: swift-crypto:20.04-5.3
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  cmake:
    image: swift-crypto:20.04-5.3

  shell:
    image: swift-crypto:20.04-5.3
