version: "3"

services:

  runtime-setup:
    image: swift-crypto:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  test:
    image: swift-crypto:22.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  cmake:
    image: swift-crypto:22.04-5.7

  shell:
    image: swift-crypto:22.04-5.7
