version: "3"

services:

  runtime-setup:
    image: swift-crypto:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"

  test:
    image: swift-crypto:22.04-5.10
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  cmake:
    image: swift-crypto:22.04-5.10
    
  cxx-interop-build:
    image: swift-crypto:22.04-5.10

  shell:
    image: swift-crypto:22.04-5.10
