version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-urlsession:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  test:
    image: *image
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      # Disable strict concurrency checking as it intersects badly with
      # warnings-as-errors on 5.10 and later as SwiftPMs generated test manifest
      # has a non-sendable global property.
      # - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: *image
